# Generated by Django 4.0.2 on 2022-04-05 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portifolioapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='image',
            new_name='projectimage',
        ),
    ]
