# Generated by Django 4.0.2 on 2022-04-06 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portifolioapp', '0002_rename_image_project_projectimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='projectimage',
            new_name='project_image',
        ),
    ]
